apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: php
  namespace: lnmp
  labels:
    app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels: 
       app: php
    spec:
      containers:
      - name: php
        image: docker.io/hermsi/alpine-fpm-php:7.2.8
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: nfs-pv
          mountPath: /usr/html
      volumes:
      # 宿主机上的目录
      - name: nfs-pv
        nfs:
          path: /mnt/nfs/wordpress
          server: 192.168.13.142
---
apiVersion: v1
kind: Service
metadata:
  name: php-svc
  namespace: lnmp
  labels:
    app: php
spec:
  #type: NodePort
  selector:
    app: php
  ports:
  - port: 9000
    targetPort: 9000
  clusterIP: None
